apiVersion: apps/v1
kind: Deployment
metadata:
  name: gin-web-server
  namespace: cci-namespace-test1
  labels:
    app: gin-web-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gin-web-server
  template:
    metadata:
      labels:
        app: gin-web-server
    spec:
      containers:
        - name: gin-web-server
          image: swr.ap-southeast-3.myhuaweicloud.com/yiran4starz/gin-web-server:latest
          resources:
            limits:
              cpu: "1"
              memory: 2Gi
            requests:
              cpu: "1"
              memory: 2Gi
      imagePullSecrets:
        - name: imagepull-secret

---

apiVersion: v1
kind: Service
metadata:
  name: gin-web-server
  namespace: cci-namespace-dev-01
spec:
  type: ClusterIP
  selector:
    app: gin-web-server
  ports:
    - port: 8081
      targetPort: 8081