apiVersion: apps/v1
kind: Deployment
metadata:
  name: gin-web-server
  namespace: argo-app
  labels:
    app: gin-web-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gin-web-server
  template:
    metadata:
      labels:
        app: gin-web-server
    spec:
      containers:
        - name: gin-web-server
          image: swr.ap-southeast-3.myhuaweicloud.com/liuyiran/gin-web-server:latest
          resources:
            limits:
              cpu: "1"
              memory: 2Gi
            requests:
              cpu: "1"
              memory: 2Gi
      imagePullSecrets:
        - name: default-secret

---

apiVersion: v1
kind: Service
metadata:
  name: gin-web-server
  namespace: argo-app
spec:
  type: ClusterIP
  selector:
    app: gin-web-server
  ports:
    - port: 8080
      targetPort: 8080