apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-evs-auto
  namespace: test-ns
  annotations:
    everest.io/disk-volume-type: SAS    # 云硬盘的类型
  labels:
    failure-domain.beta.kubernetes.io/region: ap-southeast-3   # 替换为您待部署应用的节点所在的区域
    failure-domain.beta.kubernetes.io/zone: ap-southeast-3a       # 替换为您待部署应用的节点所在的可用区
spec:
  accessModes:
  - ReadWriteOnce               # 云硬盘必须为ReadWriteOnce
  resources:
    requests:
      storage: 10Gi             # 云硬盘大小，取值范围 1-32768
  storageClassName: csi-disk    # StorageClass类型为云硬盘
